# Generated by Django 5.2.5 on 2026-04-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(blank=True, help_text='Auto-generated tracking ID (e.g. CMP-2026-ABC123)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Full name of complainant', max_length=255)),
                ('cnic', models.CharField(help_text='13-digit CNIC without dashes', max_length=13)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('category', models.CharField(choices=[('infrastructure', 'Infrastructure'), ('education', 'Education'), ('health', 'Health'), ('water', 'Water & Sanitation'), ('electricity', 'Electricity'), ('security', 'Security & Law'), ('environment', 'Environment'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField(help_text='Detailed description of the complaint')),
                ('attachment', models.FileField(blank=True, help_text='Optional attachment (image or PDF, max 5MB)', null=True, upload_to='complaints/attachments/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('admin_note', models.TextField(blank=True, help_text='Internal note by admin (visible to citizen when resolved/denied)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Complaint',
                'verbose_name_plural': 'Complaints',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tracking_id'], name='complaints__trackin_aa9cb6_idx'), models.Index(fields=['cnic'], name='complaints__cnic_6da6b2_idx'), models.Index(fields=['status', '-created_at'], name='complaints__status_f077e8_idx')],
            },
        ),
    ]
