# Generated by Django 6.0.4 on 2026-04-24 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='MNA Portal', max_length=255)),
                ('site_message', models.TextField(blank=True, help_text='Main message/tagline for the site')),
                ('intro', models.TextField(blank=True, help_text='Introduction text for landing page')),
                ('intro_image', models.ImageField(blank=True, help_text='Introduction section image', null=True, upload_to='public/intro/')),
                ('vision', models.TextField(blank=True, help_text='Organization vision')),
                ('mission', models.TextField(blank=True, help_text='Organization mission')),
                ('values', models.TextField(blank=True, help_text='Organization values')),
                ('about', models.TextField(blank=True, help_text='About section')),
                ('logo', models.ImageField(blank=True, help_text='Organization logo', null=True, upload_to='public/logo/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Public Settings',
                'verbose_name_plural': 'Public Settings',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('excerpt', models.CharField(blank=True, help_text='Short summary shown in listings', max_length=500)),
                ('image', models.ImageField(blank=True, null=True, upload_to='public/news/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=False, help_text='Show this news prominently')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['-published_at'], name='public_site_publish_576104_idx'), models.Index(fields=['status', '-published_at'], name='public_site_status_2b4c61_idx')],
            },
        ),
    ]
