# Generated by Codex on 2026-04-28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(editable=False, max_length=16, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('cnic', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='public/complaints/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('declined', 'Declined')], default='submitted', max_length=20)),
                ('admin_remarks', models.TextField(blank=True)),
                ('admin_attachment', models.FileField(blank=True, null=True, upload_to='public/complaints/admin/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['tracking_number'], name='public_site_trackin_d29cc9_idx'),
                    models.Index(fields=['cnic'], name='public_site_cnic_b1928a_idx'),
                    models.Index(fields=['status', '-created_at'], name='public_site_status_ff8300_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='ComplaintUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('declined', 'Declined')], max_length=20)),
                ('comment', models.TextField(blank=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='public/complaints/updates/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='public_site.complaint')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['status', '-created_at'], name='public_site_status_a7d0f5_idx'),
                    models.Index(fields=['complaint', '-created_at'], name='public_site_complai_4a4c22_idx'),
                ],
            },
        ),
    ]
