# Generated by Django 6.0.4 on 2026-04-28 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0002_complaint_and_updates'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('quote', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('featured', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', '-created_at'],
            },
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='public_site_trackin_2a8d3a_idx',
            old_name='public_site_trackin_d29cc9_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='public_site_cnic_68a6b0_idx',
            old_name='public_site_cnic_b1928a_idx',
        ),
        migrations.RenameIndex(
            model_name='complaint',
            new_name='public_site_status_9094ed_idx',
            old_name='public_site_status_ff8300_idx',
        ),
        migrations.RenameIndex(
            model_name='complaintupdate',
            new_name='public_site_status_4c868e_idx',
            old_name='public_site_status_a7d0f5_idx',
        ),
        migrations.RenameIndex(
            model_name='complaintupdate',
            new_name='public_site_complai_2d0425_idx',
            old_name='public_site_complai_4a4c22_idx',
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='achievements',
            field=models.TextField(blank=True, help_text='Line-separated achievements or focus areas'),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='constituency',
            field=models.CharField(blank=True, help_text='e.g. NA-239 Karachi', max_length=255),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='designation',
            field=models.CharField(blank=True, help_text='e.g. Member of the National Assembly', max_length=255),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='district',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='facebook_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='hero_statement',
            field=models.TextField(blank=True, help_text='Short prominent line used in the hero area'),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='instagram_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='leader_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='office_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='office_hours',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='x_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='publicsettings',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
    ]
