# Generated by Django 6.0.4 on 2026-08-06 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0011_news_and_portfolio_image_galleries'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='portfolioscheme',
            new_name='public_site_status_060349_idx',
            old_name='public_site_status_8d5856_idx',
        ),
        migrations.RenameIndex(
            model_name='portfolioscheme',
            new_name='public_site_union_c_359518_idx',
            old_name='public_site_union_c_397d92_idx',
        ),
        migrations.RenameIndex(
            model_name='teammember',
            new_name='public_site_status_2c9094_idx',
            old_name='public_site_status_9f3526_idx',
        ),
        migrations.RenameIndex(
            model_name='teammember',
            new_name='public_site_feature_f62e4d_idx',
            old_name='public_site_feature_572287_idx',
        ),
    ]
