# Generated by Django 6.0.4 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public_site', '0012_rename_public_site_status_8d5856_idx_public_site_status_060349_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicsettings',
            name='about_image',
            field=models.ImageField(blank=True, help_text='Dedicated About page image', null=True, upload_to='public/about/'),
        ),
    ]
