# Generated by Django 6.0.4 on 2026-04-12 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schemecategory',
            old_name='key',
            new_name='slug',
        ),
        migrations.RemoveField(
            model_name='schemecategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='schemecategory',
            name='is_active',
        ),
        migrations.AddField(
            model_name='schemecategory',
            name='scheme_id',
            field=models.CharField(default='TEMP', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
