# Generated by Django 6.0.4 on 2026-04-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_rename_key_schemecategory_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schemecategory',
            name='scheme_id',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='schemecategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
